# Generated by Django 3.0.6 on 2020-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('wallet_id', models.CharField(max_length=20, verbose_name='ID')),
                ('wallet_nominal', models.IntegerField(verbose_name='Nominal')),
                ('wallet_value', models.FloatField(verbose_name='Value')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
