# Generated by Django 3.0.6 on 2020-05-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_course',
            name='wallet_char_code',
            field=models.CharField(default=5, max_length=10, verbose_name='Char_code'),
            preserve_default=False,
        ),
    ]
