# Generated by Django 3.0.6 on 2020-05-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_wallet_course_wallet_char_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_indentificator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=200, verbose_name='Название валюты')),
                ('wallet_id', models.CharField(max_length=20, verbose_name='ID')),
                ('wallet_char_code', models.CharField(max_length=10, verbose_name='Char_code')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Wallet_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_nominal', models.IntegerField(verbose_name='Nominal')),
                ('wallet_value', models.FloatField(verbose_name='Value')),
                ('date', models.DateField(verbose_name='Data')),
                ('wallet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.Wallet_indentificator')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
        migrations.DeleteModel(
            name='Wallet_course',
        ),
    ]
