# Generated by Django 3.0.6 on 2020-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20200507_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_value',
            old_name='wallet_name',
            new_name='wallet',
        ),
    ]
